# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
inhibit_all_warnings!
# use_frameworks!

workspace 'ZWDevelopmentKit'



project ‘./ZWDevelopmentKit.xcodeproj'
target :ZWDevelopmentKitExample do

end




